DM-44026: first draft of technote on wavelength-dependent PSFs
lsst-dm/dmtn-291 pull request #2
Opened 2024-05-04 13:11 UTC by TallJimbo

2024-05-06 20:27 UTC, leannep requested changes
Great start

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +The ``zeroth-order'' challenge is photometric calibration, where a substantial fraction of the wavelength dependence comes from hardware we can inspect directly (filters, quantum efficiency, antirefl
```suggestion
The ``zeroth-order'' challenge is photometric calibration, where a substantial fraction of the wavelength dependence comes from hardware we can inspect directly (filters, sensor quantum efficiency, antireflective coatings, etc), and we have a comprehensive plan involving a tunable laser and the collimated beam projector to measure the wavelength-dependent throughput directly and incorporate it into our flat fielding.
```

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +The ``zeroth-order'' challenge is photometric calibration, where a substantial fraction of the wavelength dependence comes from hardware we can inspect directly (filters, quantum efficiency, antirefl
QE is not hardware itself but a characteristic of the sensors

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +Chromatic seeing from the atmosphere \emph{roughly} scales the size of the PSF as $\lambda^{-1/5}$ \citep{1966JOSA...56.1372F,2015ApJ...807..182M}, but making use of the theory behind this in PSF mod
Something is wrong with the citation, it renders with a '?'

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +\item Even if we did know the sub-band SED of each pixel contributing to a coadd prior to resampling, the result would be an effective coordinate transform that sometimes changes rapidly over just pi
```suggestion
\item Even if we did know the sub-band SED of each pixel contributing to a coadd prior to resampling, the result would be an effective coordinate transform that sometimes changes rapidly over just pixels (e.g. where a bright blue star's flux becomes dominant over a neighboring red star's); this cannot be approximated as a locally affine transformation, and hence our decomposition of the transfer function into PSF and coordinate transform breaks down on the coadd, and its PSF is ill-defined.
```

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +For the astrometric calibration we are focused on here, this is expected to run on large sky tiles (at least the size of the full focal plane) and include measurements all visits that overlap that ti
```suggestion
For the astrometric calibration we are focused on here, this is expected to run on large sky tiles (at least the size of the full focal plane) and include measurements of all visits that overlap that tile.
```

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +This approach to DCR in astrometric calibration is the standard approach, and while we do not yet have it all running, the code we are using is at its core the same used in DECam astrometric calibrat
```suggestion
This approach to DCR in astrometric calibration is the standard approach, and while we do not yet have it all running, the code we are using is at its core the same used in DECam astrometric calibrations \citep{2017PASP..129g4503B}. 
We currently envisage having this working on the multi-epoch DP2 dataset. 
```

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +This approach to DCR in astrometric calibration is the standard approach, and while we do not yet have it all running, the code we are using is at its core the same used in DECam astrometric calibrat
I would omit any reference to DP1 - if we can do it we will and it will be an added bonus (as opposed to something not delivered)

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +We hope to have this step working by DR1, but given the compressed commissioning timeline and the difficulty of making real progress before LSSTCa data is available, this is hard to guarantee.
```suggestion
We aim to have this step working by DR1, but given the compressed commissioning timeline and the difficulty of making real progress before LSSTCam data is available, this is hard to guarantee.
```

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +We hope to have this step working by DR1, but given the compressed commissioning timeline and the difficulty of making real progress before LSSTCa data is available, this is hard to guarantee.
"the difficulty of making real progress before LSSTCam data" -> is this due to the need for multi-epoch full-focal-plane data? or time/resources/competing priorities? If the former, suggest stating that explicitly so that it is clear that this is not a problem that can be solved by throwing more resources at it, or reprioritizing.

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +We hope to have this step working by DR1, but given the compressed commissioning timeline and the difficulty of making real progress before LSSTCa data is available, this is hard to guarantee.
Perhaps is would be better to give DR2 as the goal and state that DR1 is a stretch goal?

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +We fully expect this to be the coaddition method used for DP2 (and, if coadds are built, DP1).
```suggestion
We fully expect this to be the coaddition method used for DP2. 
```

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +We fully expect this to be the coaddition method used for DP2 (and, if coadds are built, DP1).
Suggest to scrap any reference to DP1. We are only promising single-epoch data products for DP1. *if* we make coadds and they look good we can augment the DP1 dataset at the time of release.

2024-05-06 20:27 UTC, leannep commented on DMTN-291.tex
> +The full Source catalog will be produced by redetecting and remeasuringdown to 5-sigma depth, and is considerably less clean, even though it will be built with better PSFs, backgrounds, and other cal
```suggestion
The full Source catalog will be produced by redetecting and remeasuring down to 5-sigma depth, and is considerably less clean, even though it will be built with better PSFs, backgrounds, and other calibrations.
```

2024-05-07 13:56 UTC, TallJimbo commented on DMTN-291.tex
> +Chromatic seeing from the atmosphere \emph{roughly} scales the size of the PSF as $\lambda^{-1/5}$ \citep{1966JOSA...56.1372F,2015ApJ...807..182M}, but making use of the theory behind this in PSF mod
It looks like none of my recent additions to lsst-texmf have been picked up in this render.  I think I followed the right process, including merging my lsst-texmf branch to main and updating the submodule.

2024-05-07 13:56 UTC, TallJimbo commented on DMTN-291.tex
> +We hope to have this step working by DR1, but given the compressed commissioning timeline and the difficulty of making real progress before LSSTCa data is available, this is hard to guarantee.
It's a combination of the two - I don't think we can make much progress until we get at least real ComCam data, and only some of that will carry over to LSSTCam.  And then if it was our top priority I'm pretty sure we could get it done, but it's quite likely there will be bigger problems we'll need to focus on instead.

2024-05-22 18:03 UTC, RobertLuptonTheGood reviewed
I'm going to discuss the last section with Jim in person

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +Chromatic seeing from the atmosphere \emph{roughly} scales the size of the PSF as $\lambda^{-1/5}$ \citep{1966JOSA...56.1372F,2015ApJ...807..182M}, but making use of the theory behind this in PSF mod
I see "roughly" but 1/5 is Kolmogorov, and usually it's closer to 1/4;  I'd quote the range.
However, I don't see how this requires knowledge of the structure of the atmosphere.  All that knowledge (C_N^2 etc.) is encapsulated in r_0, which is directly measured and the scaling with lambda comes from the assumption about the turbulent spectrum.  Maybe that's what you mean?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +
Isn't this a convolution?  And probably not an issue for this audience as the discussion of seeing is tangential, but $T$ usually means the OTF, the Fourier transform of the PSF, in that community.

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +Its dependence on $\mathbf{r}$ and $\mathbf{x}$ encodes both the PSF $\phi$ and the coordinate transform $\mathbf{S}$ from sky to pixel coordinates (frequently called the WCS, or ``world coordinate s
Will using the acronym WCS here trigger e.g. Dave Monet?  What you say is clear

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +Note that there is no spatial variation in the PSF or the photometric calibration in either case - that is the first reason this is a local approximation only.
Sorry, more notation.   Željko will object that he's written photometric calibration white papers which use S as the throughput as a function of frequency (I think; certainly a photometric symbol).  He has a point, as you'll be looking at SEDs too

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +Thankfully this second local approximation is almost always valid, with small regions affected by strong lateral electric field differences in the detectors a notable exception, e.g. the ``tape bumps
or small-scale tree-rings, or "epoxy blobs" in HSC, which we don't correct for.  Incidentally, I'm about to start correcting for them in PFS

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +But it is important to note that this decomposition is motivated by its local applicability, and hence there is a degeneracy between the spatial variation in the PSF and the coordinate transform from
And the measured centre of the PSF, not just the variation thereof -- we could offset the PSF model and the astrometry and it wouldn't change the science. 

I'd have written "centroid" until a few weeks ago, when I realised that the diffraction spikes (or worse optical LSF in a spectrograph) don't have a well defined centroid.  I don't think this matters in practice!

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +\item If the coordinate transform is wavelength-dependent, we cannot resample images to a common coordinate system to build coadds or perform image subtraction without knowing the SED of each pixel w
I don't think that a "pixel SED" is well defined.  It would be for a Kaiser coadd, where we're estimating the deconvolved sky and then reconvolving with a chosen PSF;  but then the choice of that PSF is what you're discussing.
I'm not sure if this is worth elucidating here.

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +\item Even if we did know the sub-band SED of each pixel contributing to a coadd prior to resampling, the result would be an effective coordinate transform that sometimes changes rapidly over just pi
I'm not sure if this is right.  If you had sub-band SEDs for each pixel (see previous comment!) you'd have sliced the image into multiple images, each with a well-defined transformation.  That would handle the blue-and-red-light in a pixel problem.

I'm not saying that I disagree with the conclusion.

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +A major implication of this convention is that the PSF model cannot not be simultaneously centered (i.e. have zero first moment under a certain weight function) for all wavelengths when a non-isotrop
I think that a weighted first-order moment is a sensible definition, but it's actually only _optimal_ for a Gaussian PSF.  In that limit -- and I think _only_ in that limit -- adaptive moments provide a way to estimate that weighting function.   In general we will have to specify this externally to the centroiding algorithm, or accept some loss of efficiency (which is probably fine).

Again, I don't think that this changes any of your conclusions

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +A corollary of this is that the PSF model \emph{is} centered for \emph{some} SED, which we will refer to as the ``centering SED``.
For some SED and some weighting function, which may or may not be chromatic.   If we choose a chromatic weight function, it isn't actually obvious to me that there is only one SED which results in a centered PSF.   Actually, given weird enough SEDs, I bet that there are a range (e.g. two delta functions at suitable wavelengths)

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +In practice, we expect the centering SED to be a hard-to-back-out average over the SEDs of the stars that go into our astrometric fitting.
I think that the choice of weight functions probably _does_ matter here.  It's not the same for every epoch, so the "centering SED" probably isn't either.  Do we explicitly offset the PSF models to fix this?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +This generates lists of preliminary sources that are then spatially matched to each other and the Gaia catalog, and fed to our multi-epoch photometric and astrometric calibration routines.
Are we requiring that all these "sources" are stars?  I think so; astrometry with galaxies is hard (hence my interest in diffim kernels)

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +The coordinate transform model will include static or nearly static optical and sensor-level distortion models that are fit in advance, composed with pointing, rotation, and atmospheric turbulence te
I'd say, "optical and camera" as the CCDs will probably move

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +  \item The SEDs used to derive the DCR correction come from colors that are themselves derived from magnitudes measured independently, and then spatially matched (rather than forced photometry).
Clarify that we are not using GAIA colours here?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +The full parameterization of this model is TBD, including how wavelength dependence will be represented, but prior art (from the Dark Energy Survey collaboration, still in prep) suggests a simple reg
Add "such as $g - i$" ?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +The linchpin of our plan to ensure consistency between the PSF model and coordinate transform is that the PSF modeling will be fed star positions derived by projecting the best-fit position for each
"also incorporating" -> "after correcting for"?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +To our knowledge using projected positions rather than per-visit centroids has not been tried before, and it may prove difficult for unexpected reasons.
I was probably skimming too fast, but what do you mean by "projected positions"?  Model positions?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +Coadds will be built in small cells, over which the set of input visits is fixed (visits that only partially overlap a cell are not included) and the PSF can be assumed to be spatially constant.
I'd explain "the PSF can be assumed to be spatially constant".  Say that we plan to make the cells small enough that the PSF is essentially constant, and that this assumption is not fundamental?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +The wavelength dependence of the PSF will be included, for example by also coadding the derivative of the PSF model with respect to one or more parameters that represent the SED.
I don't know what this means.  We don't have per-source SEDs (as you point out, more than one source can lie within a pixel), so aren't we using a single PSF per epoch?  Do you mean we'll choose the SED of the PSF to be e.g. flat in $\nu F_\nu$ or something different?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +Cell-based coaddition (including PSF coaddition) has been implemented but is still being tested prior to full integration with the main pipeline.
Do we want to say that we are exploring this in conjunction with DES, or that the Y6 DES release is using the same approach (is it?).   Something to make cell-based coadds less scary to those outside Rubin?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +In particular, we do not currently plan to perform a full photometric redshift analysis to infer the SEDs of galaxies prior to performed PSF-based measurements on them; not only would this require at
performed -> performing ?

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +In particular, we do not currently plan to perform a full photometric redshift analysis to infer the SEDs of galaxies prior to performed PSF-based measurements on them; not only would this require at
Do we want to mention that Rubin DM _is_ expecting to put out some photo-z estimates?  It's tangential to this note, but I wouldn't want to scare people.

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +In particular, we do not currently plan to perform a full photometric redshift analysis to infer the SEDs of galaxies prior to performed PSF-based measurements on them; not only would this require at
We don't actually need "sophisticated photo-z"s;  all we need is the SED given the colours, and a 4000\AA and a Lyman break are the same for us.   But I think your point remains

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +The full Source catalog will be produced by redetecting and remeasuring down to 5-sigma depth, and is considerably less clean, even though it will be built with better PSFs, backgrounds, and other ca
"to 5-sigma depth"  on the coadds?  And "less clean" is a statement about the sky, not the processing

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +In the meantime, we expect machine learning-based reliability algorithms to do a reasonably good job of rejecting DCR-induced dipoles.
Dipoles simply don't seem to have been the problem that people expected, and I don't know why.   If they _are_ a problem, I'd expect to be able to handle them without resorting to ML (or, to put it another way, to be able to make the ML's job easier by cleaning the samples);  whether that's necessary remains to be seen.

2024-05-22 18:03 UTC, RobertLuptonTheGood commented on DMTN-291.tex
> +\section{Sub-band SED Inference from PSFs}
I'm going to discuss this in person with Jim, so I'll submit the other $\pm$ picky comments now

2024-06-07 15:14 UTC, TallJimbo commented on DMTN-291.tex
> +Chromatic seeing from the atmosphere \emph{roughly} scales the size of the PSF as $\lambda^{-1/5}$ \citep{1966JOSA...56.1372F,2015ApJ...807..182M}, but making use of the theory behind this in PSF mod
Rewriting the scaling as a range as suggested.

All I'm trying to say here with "structure" is that there are latent variables in a physical model we have to assume or infer from the data, and I've reworded to just say that it's a hard inference problem.

It's probably irrelevant for this note, but I'm curious what you mean by saying that `r_0` is "directly measured".  From what data?

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +
It's a convolution only if the difference of `x` and `r` is all that affects `T`.  This is a general function of both sky position and pixel position, so it can represent spatially-varying convolutions, coordinate transforms, etc. as well.

I'll switch from `T` to `\Psi` throughout.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +Its dependence on $\mathbf{r}$ and $\mathbf{x}$ encodes both the PSF $\phi$ and the coordinate transform $\mathbf{S}$ from sky to pixel coordinates (frequently called the WCS, or ``world coordinate s
I figure it's still a useful reference as a way to clarify what I'm talking about.  I think the assumption that WCS == FITS WCS is rarely made these days.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +Note that there is no spatial variation in the PSF or the photometric calibration in either case - that is the first reason this is a local approximation only.
I'll switch from `S` to `A` throughout.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +Thankfully this second local approximation is almost always valid, with small regions affected by strong lateral electric field differences in the detectors a notable exception, e.g. the ``tape bumps
I've added another sentence noting that tree rings are at a scale that is worrying, but that current corrections for those still make this assumption and appear to get away with it.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +But it is important to note that this decomposition is motivated by its local applicability, and hence there is a degeneracy between the spatial variation in the PSF and the coordinate transform from
Agreed, but I think at this stage in the note bringing this up would be more of a distraction; it's a point I think I'm aleady making later.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +\item If the coordinate transform is wavelength-dependent, we cannot resample images to a common coordinate system to build coadds or perform image subtraction without knowing the SED of each pixel w
Agreed; for "pixel SED" we need to state what it is that a pixel represents in terms of some likelihood, and I think that's well defined for Kaiser coadds and not obviously defined otherwise.  But I think I'd rather not get into that here.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +\item Even if we did know the sub-band SED of each pixel contributing to a coadd prior to resampling, the result would be an effective coordinate transform that sometimes changes rapidly over just pi
Yes, I've thought about that kind of Kaiser coadd and even did a little math on it.  At best the coadds for different sub-bands have really strongly correlated values, and unless you have so many sub-bands that you Nyquist-sample the spectral-domain PSF, the correlation structure is really messy and you can't use FFTs to solve it.

But I think again that's probably a distraction for anyone else reading this note.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +A major implication of this convention is that the PSF model cannot not be simultaneously centered (i.e. have zero first moment under a certain weight function) for all wavelengths when a non-isotrop
I'll fix the parenthetical to say that the PSF cannot be centered at all wavelengths for any useful definition of "centered", which I think is more general and still true (though "useful" may be doing some heavy lifting).

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +A corollary of this is that the PSF model \emph{is} centered for \emph{some} SED, which we will refer to as the ``centering SED``.
I certainly hadn't considered the possibility of using a chromatic weight function.  I don't think it'd help with anything, and it's make for a chicken-and-egg-problem.  But I suppose I should be explicit that I'm assuming it's achromatic.

I agree that saying that the PSF model is centered for one SED is an oversimplification, and I'll weaken that language.  It's an integral constraint.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +In practice, we expect the centering SED to be a hard-to-back-out average over the SEDs of the stars that go into our astrometric fitting.
I think my hope was that by fitting the astrometry and PSF as I proposed in later sections, the "centering SED" would end up corresponding to some local average of the SEDs of the various stars that contribute to the astrometric fit, weighted by how they contributed to the local result of the fit and PSF model.  And then the "centering SED" would end up being roughly the same for every epoch, since the stars that go into the astrometric fit should be bright enough that they appear on almost every epoch are are selected jointly across all epochs.  There are a lot of assumptions there, but I don't have an alternative in mind, and I think they're reasonable assumptions for the kind of first-order correction we need to do.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +This generates lists of preliminary sources that are then spatially matched to each other and the Gaia catalog, and fed to our multi-epoch photometric and astrometric calibration routines.
Yes, and I think chromatic astrometry with galaxies is even harder, because their SEDs are hard to infer, and I don't think difference-kernel games help with that (at least not as long as those kernels are achromatic).

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +To our knowledge using projected positions rather than per-visit centroids has not been tried before, and it may prove difficult for unexpected reasons.
Yes, model positions.  Will use that instead.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +The wavelength dependence of the PSF will be included, for example by also coadding the derivative of the PSF model with respect to one or more parameters that represent the SED.
I'll rewrite this to say that we'll expand the wavelength dependence of the PSF at each point in some basis and coadd the basis expansion.  It'll probably be convenient if it's the sort of basis where there's a zeroth-order term that corresonds to a flat spectrum or something similarly convenient, but it doesn't have to be for this scheme to work.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +In particular, we do not currently plan to perform a full photometric redshift analysis to infer the SEDs of galaxies prior to performed PSF-based measurements on them; not only would this require at
I'll just drop the second argument about not wanting to do sophisticated photo-zs; I don't think it adds much.

2024-06-07 18:06 UTC, TallJimbo commented on DMTN-291.tex
> +The full Source catalog will be produced by redetecting and remeasuring down to 5-sigma depth, and is considerably less clean, even though it will be built with better PSFs, backgrounds, and other ca
I'll say that matching them would be less clean due to increased blending.

2024-06-07 18:08 UTC, TallJimbo commented
@leannep , PR is still in the "changes requested" state from you, so I'll hold off merging for now.  I've just gone ahead and removed the timeline information that I think was your biggest concern, as I think a technical document like this isn't the best place for that information anyway.

2024-06-13 03:16 UTC, leannep approved these changes

2024-06-13 03:43 UTC, merged